---
- hosts: "all"
  tasks:
    - name: install nginx
      become: yes
      apt: name=nginx state=latest
    - name: start nginx service
      service:
        name: nginx
        state: started
      become: yes
    - name: clean default html files
      become: yes
      file:
        state: absent
        path: "{{ htmldir }}"
    - name: copy the content from git
      become: yes
      git:
        force: yes
        repo: "{{ gitrepo }}"
        dest: "{{ htmldir }}"
    - name: restart service
      service:
        name: nginx
        state: restarted
      become: yes
